---
- name: Manage a pool
  bigip_pool:
    server: "{{ inventory_hostname }}"
    user: "{{ username }}"
    password: "{{ password }}"
    name: "{{ name }}"
    validate_certs: "false"
    state: "{{ state }}"
    monitors:
      - "{{ monitor }}"
  delegate_to: localhost
...
