---
- name: Manage the HTTP Monitor
  bigip_monitor_http:
    name: "my_http_monitor"
    user: "{{ username }}"
    password: "{{ password }}"
    server: "{{ inventory_hostname }}"
    send: "GET /\r\n"
    receive: ""
    validate_certs: "false"
    state: "{{ state }}"
  delegate_to: localhost
...
