---
- name: Configure a appsvcs iapp service using parameters in JSON document
  bigip_iapp_service:
    name: "appsvcs"
    user: "{{ username }}"
    password: "{{ password }}"
    server: "{{ inventory_hostname }}"
    template: "appsvcs_integration_v2.0.003"
    validate_certs: "false"
    state: "{{ state }}"
    parameters: "{{ lookup('file', 'appsvcs.json') }}"
  delegate_to: localhost
...
